using System.Reflection;
using System.Text;
using Expanse.Domain.Colonies;

if (args.Length != 1) throw new ArgumentException("Pass the absolute generated .cs path.");
var types = new SortedDictionary<string, Type>(StringComparer.Ordinal);
void Visit(Type t)
{
    if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(List<>)) { Visit(t.GenericTypeArguments[0]); return; }
    if (t == typeof(string) || t.IsValueType) return;
    if (t.Namespace != typeof(ColonyState).Namespace || !t.IsSealed || t.GetConstructor(Type.EmptyTypes) == null)
        throw new InvalidOperationException("Unsupported persisted type " + t);
    if (!types.TryAdd(t.Name, t)) return;
    foreach (var p in Members(t)) Visit(p.PropertyType);
}
static PropertyInfo[] Members(Type t) => t.GetProperties(BindingFlags.Public | BindingFlags.Instance).Where(p => p.CanRead && p.CanWrite && p.GetIndexParameters().Length == 0).OrderBy(p => p.Name, StringComparer.Ordinal).ToArray();
static string Name(Type t) => t.IsGenericType ? t.GetGenericTypeDefinition() == typeof(List<>) ? "List<" + Name(t.GenericTypeArguments[0]) + ">" : t == typeof(double?) ? "double?" : throw new InvalidOperationException("Unsupported generic " + t) : t.Name;
Visit(typeof(ColonyState));
var b = new StringBuilder("// Generated by dev/Expanse.Colony.CopyGenerator. Do not edit by hand.\n#nullable enable\nusing System;\nusing System.Collections.Generic;\nnamespace Expanse.Domain.Colonies\n{\n    internal static partial class ColonyStateDetachedCopy\n    {\n");
b.AppendLine("        internal static readonly string[] ExpectedShape = new string[]").AppendLine("        {");
foreach (var type in types.Values) foreach (var p in Members(type)) b.AppendLine($"            \"{type.Name}.{p.Name}:{Name(p.PropertyType)}\",");
b.AppendLine("        };");
foreach (var type in types.Values)
{
    var members = Members(type);
    var objectBytes = 2 + Math.Max(0, members.Length - 1) + members.Sum(p => Encoding.UTF8.GetByteCount(p.Name) + 3);
    b.AppendLine($"        internal static {type.Name} Clone({type.Name}? value, CopyBudget budget, int depth)").AppendLine("        {");
    b.AppendLine("            budget.Node(depth);").AppendLine("            if (value == null) { budget.Add(4); return null!; }");
    b.AppendLine($"            budget.Add({objectBytes});").AppendLine($"            return new {type.Name}").AppendLine("            {");
    foreach (var p in members)
    {
        bool list = p.PropertyType.IsGenericType && p.PropertyType.GetGenericTypeDefinition() == typeof(List<>);
        b.AppendLine($"                {p.Name} = {(list ? "CloneList" : "Clone")}(value.{p.Name}, {(list ? "Clone, " : "")}budget, depth + 1),");
    }
    b.AppendLine("            };").AppendLine("        }");
}
b.AppendLine("    }").AppendLine("}");
File.WriteAllText(args[0], b.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated {types.Count} persisted record types and {types.Values.Sum(t => Members(t).Length)} properties.");
