from pathlib import Path
import re

root = Path(__file__).parent / 'site-existing-base-open' / 'dist'
quick = (root / 'colony-mvp-quick-start.html').read_text(encoding='utf-8')
style = re.search(r'<style>(.*?)</style>', quick, re.S).group(1)
header = re.search(r'<header class="topbar">.*?</header>', quick, re.S).group(0).replace(' aria-current="page"', '')
header = header.replace('<a href="colony-mvp-quick-start.html">Quick start</a>', '<a href="colony-mvp-quick-start.html">Quick start</a><a href="use-existing-base.html" aria-current="page">Existing base</a>')
body = '''
<div class="qs-eyebrow">Minmus MVP / existing facilities</div>
<h1>Use my existing base</h1>
<p class="qs-intro">Keep the facilities you have already deployed. Adoption, home qualification, reserves and tank service are separate steps. Start with the short path below.</p>
<aside class="qs-note"><strong>Already adopted, but startup says storage, power, workshop or lamp is missing?</strong> Adoption preserves a facility in the colony record. The startup planner requires qualified role assets with certification evidence; an adopted row alone does not satisfy those checks. <strong>Import Supplies — no new production investment</strong> changes the supply strategy, not these requirements. Leave <strong>Approve reviewed startup plan</strong> alone when your goal is to use existing buildings.</aside>
<p style="margin-top:24px"><strong>For reviewed actions:</strong> pause KSP, wait for the colony view to refresh, then review and apply while paused. Read each review before spending funds or changing the save.</p>
<section class="qs-steps" aria-label="Short existing-base path">
<article class="qs-step"><span class="qs-num">1</span><div><h2>Check what is already adopted</h2><p>Open <strong>Manage colony</strong>, select your registered colony, then open <strong>Founding &amp; charter</strong>. In <strong>TASK</strong>, choose <strong>Adopt an existing facility</strong>. If the facility already appears as adopted, skip adopting it again. Zero homes means it has no qualified homes; it does not mean adoption failed.</p><p>For an unowned nearby facility, select its row, choose <strong>Review facility adoption</strong>, verify its identity and site, then choose <strong>Adopt reviewed facility</strong>. It must be on the charter body and inside the charter radius. Keep the existing charter when it already describes your intended base.</p></div></article>
<article class="qs-step"><span class="qs-num">2</span><div><h2>Qualify homes, if the habitat is supported</h2><p>In <strong>Founding &amp; charter</strong> or <strong>People &amp; jobs</strong>, choose <strong>Qualify existing habitat homes</strong> when available. Select the adopted habitat, choose <strong>Review habitat homes</strong>, inspect the utility and seat checks, then choose <strong>Qualify reviewed habitat homes</strong>.</p><p><strong>If the task is absent or the review cannot qualify homes, stop this resident setup path.</strong> Adoption does not convert every MKS module, crew seat or mining vessel into supported housing. The tested ordinary habitat is a deployed KPBS Habitat Mk2 with KPBS Landing Control and a stock RTG. Existing vessel support depends on its actual parts and current utility evidence.</p></div></article>
<article class="qs-step"><span class="qs-num">3</span><div><h2>Receive Supplies and start resident support</h2><p>When eligible actions are available, use <strong>Trade → Review a resource import</strong>. Select the supplier and amount, review the paid quote, then approve it. If receiving capacity is missing, use <strong>Purchase receiving stores</strong> and review the paid staging contract first. Follow the shipment in Trade; reserves are credited after arrival.</p><p>Then use <strong>People &amp; jobs → Start resident support</strong> and inspect the qualified-home and reserve requirements. Approve only when the review passes. Support consumes colony-owned Supplies. Imported reserves do not automatically fill every installed tank.</p></div></article>
<article class="qs-step"><span class="qs-num">4</span><div><h2>Bring in a named resident</h2><p>Use <strong>People &amp; jobs → Recruit a resident</strong>. Choose an available named Kerbal, a qualified vacant home and an eligible paid passenger route. Review the fare and any Applicant fee, then approve recruitment. Arrival follows the paid journey; adoption and qualification do not create residents.</p></div></article>
</section>
<section style="margin-top:28px" aria-label="Optional operating details">
<details class="qs-summary"><summary><strong>Existing tanks, production and service</strong></summary><p style="margin-top:14px">Native machinery still operates through its KSP mods. Adoption does not certify every production role, register every tank, or start every recipe. Check the actual available actions and their reviews.</p><p><strong>Inventory → Transfer physical tanks and colony reserves</strong> handles an eligible observed stock source and direction. Review the amount and ownership before applying a transfer. This is separate from an imported reserve shipment.</p><p><strong>Maintenance → Deliver owned reserves to an installed tank</strong> reviews a supported tank top-up. It requires the relevant colony-owned resource and any stated access or workforce conditions. <strong>Configure recurring tank service</strong> is the separate policy for eligible recurring top-ups; turning on imports does not enable it.</p><p><strong>Trade → Set automatic reserve replenishment</strong> controls reserve reorders. It does not build infrastructure or guarantee support if homes, funds, capacity or routes are missing.</p></details>
<details class="qs-summary"><summary><strong>What the three Supplies strategies mean</strong></summary><p style="margin-top:14px"><strong>Import Supplies — no new production investment:</strong> choose imported food rather than committing new cultivation packages. It does not by itself order a shipment or approve a startup plan.</p><p><strong>Compare cultivation with imports — no production commitment:</strong> compare the choices without committing new production.</p><p><strong>Invest in native cultivation and raw-feed hoppers:</strong> include the native cultivation investment path. This is not an instruction to recognize all existing machinery as certified startup infrastructure.</p><p>All three are startup-plan supply choices. None removes the startup planner's qualified storage, power, workshop and lamp requirements.</p></details>
<details class="qs-summary"><summary><strong>Homes blocked, missing actions or facilities outside the site</strong></summary><p style="margin-top:14px">Load the intended landed habitat, let stock easing finish at 1x, deploy it, and use the mint <strong>I</strong> toolbar button → <strong>Expanse Foundations → Anchor base</strong> when supported. Wait for the anchored status. Pause, refresh and review again. Anchoring alone does not certify utilities or qualify seats.</p><p>If there is still no eligible home review, read the reason and treat it as a qualification limit. The current MVP has no general one-click commissioning step for all existing mixed MKS buildings. A power or mining vessel may be adoptable while housing checks remain unavailable.</p><p>If an unowned facility is absent from adoption, check its body and distance from the charter site. Being elsewhere on Minmus does not put it inside the charter radius. Do not create another charter merely to work around an unexplained missing row.</p><p>If a review becomes stale, pause and refresh before reviewing again. If it asks for new packages you do not intend to build, leave that startup approval alone and return to the individual workflows above.</p></details>
<details class="qs-summary"><summary><strong>Optional automatic arrivals</strong></summary><p style="margin-top:14px">After homes and support work, use <strong>Founding &amp; charter → Edit existing charter</strong>, set <strong>Founding residents</strong>, and inspect <strong>Advanced charter policy → Automatic within charter</strong>. Review and apply only the intended limits. Eligible named arrivals still require a vacant qualified home, sustainable reserves, funds and a paid route seat. This policy does not build another habitat.</p></details>
</section>
<a class="qs-back" href="colony-build.html">Back to Colony build</a> · <a href="colony-mvp-quick-start.html">Tested ordinary habitat quick start</a>
'''
page = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Use deployed Minmus facilities without confusing adoption with certified startup construction: homes, reserves, tank service and residents."><title>Use my existing base — Expanse Foundations</title><link rel="stylesheet" href="styles.css"><style>{style}\n.qs summary{{cursor:pointer;line-height:1.4}}.qs details p:last-child{{margin-bottom:0}}.qs details:not([open]){{padding-block:16px}}</style></head><body>{header}<main class="qs">{body}</main></body></html>'''
(root / 'use-existing-base.html').write_text(page, encoding='utf-8')
for name in ['colony-build.html', 'colony-mvp-quick-start.html']:
    p = root / name
    text = p.read_text(encoding='utf-8')
    link = '<a href="use-existing-base.html">Existing base</a>'
    text = text.replace('<a href="/colony-guide">Colony User Guide</a>', link + '<a href="/colony-guide">Colony User Guide</a>', 1)
    if name == 'colony-build.html':
        marker = '<section id="current"><h2>Current checkpoint</h2>'
        note = '<div class="callout"><strong>Using facilities you already built?</strong><p><a href="use-existing-base.html">Use my existing base: the short tutorial</a>. Already-adopted facilities do not automatically satisfy certified startup roles. Follow individual home, reserve and service workflows before approving any new construction.</p></div>'
        assert marker in text
        text = text.replace(marker, marker + '\n' + note, 1)
    else:
        marker = '<section class="qs-summary"'
        note = '<p class="qs-summary"><strong>Already have a mixed base?</strong> Start with <a href="use-existing-base.html">Use my existing base</a> to check adoption, supported homes and individual service workflows. The tested craft below is an optional reference, not a replacement for every existing facility.</p>\n    '
        assert marker in text
        text = text.replace(marker, note + marker, 1)
    p.write_text(text, encoding='utf-8')
print('Updated three HTML pages; existing styles and historical content preserved.')
