using Expanse.Domain;
using Expanse.WorldBridge;
using BackgroundResourceProcessing;

int passed=0, total=0;
void Test(string name,Action test) { total++;try { test();passed++;Console.WriteLine("PASS "+name); } catch(Exception ex) { Console.WriteLine("FAIL "+name+" "+ex);Environment.ExitCode=1; } }
void Check(bool condition,string reason) { if(!condition)throw new Exception(reason); }
(Vessel V,PartResource R,BackgroundResourceProcessor B,InventoryEndpoint E) Fixture(bool packed=false,bool mirror=false,double amount=10)
{
 HighLogic.LoadedSceneIsFlight=true;HighLogic.LoadedSceneIsGame=true;HighLogic.CurrentGame=new object();
 var r=new PartResource {resourceName="Ore",amount=amount,maxAmount=100};var p=new Part {persistentId=7,flightID=70,Resources=[r]};
 var b=new BackgroundResourceProcessor();var v=new Vessel {packed=packed,parts=[p],vesselModules=[b]};
 if(mirror){var s=new ProtoPartResourceSnapshot {resourceName="Ore",amount=5,maxAmount=100};s.UpdateConfigNodeAmounts();b.Inventories.Add(new ResourceInventory {FlightId=70,ResourceName="Ore",Amount=5,OriginalAmount=5,MaxAmount=100,Snapshot=s});v.protoVessel.protoPartSnapshots=[new ProtoPartSnapshot {persistentId=7,flightID=70,resources=[s]}];}
 FlightGlobals.Vessels=[v];FlightGlobals.ActiveVessel=v;
 DepotRegistryModule.Instance=new DepotRegistryModule {Registrations=[new DepotRegistration {DepotId="source",MembershipRevision=1,Anchor=7,MemberIds=[7]}]};
 var e=new InventoryEndpoint {DepotId="source",MembershipRevision=1,AnchorPersistentId=7,MemberPersistentIds=[7],MemberSetHash=OperationIdentity.ComputeMemberSetHash(7,[7]),MembershipHash=new string('a',64),Scene="Flight"};return(v,r,b,e);
}
InventoryMutationPlan Prepare(LoadedBrpInventoryGateway g,InventoryEndpoint e,long delta=-1000000)
{var r=g.Resolve(e);Check(r!=null,"resolve");var p=g.Preflight(r,[new InventoryDelta {MemberPersistentId=7,ResourceName="Ore",DeltaMicroUnits=delta}]);Check(p.Accepted,p.Reason);return p.Plan;}
Test("loaded BRP cleared inventory uses sole PartResource authority",()=>{var f=Fixture();var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded,"apply");Check(g.Synchronize(p).Succeeded,"sync");Check(f.R.amount==9&&f.B.Inventories.Count==0,"exact debit and no phantom mirror");});
Test("anchored packed loaded vessel accepts exact transfer without unanchoring",()=>{var f=Fixture(true);var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded&&g.Synchronize(p).Succeeded,"packed provider");Check(f.V.packed&&f.V.loaded&&f.R.amount==9,"physical packed condition preserved");});
Test("nonactive loaded vessel resolves selected anchor",()=>{var f=Fixture();FlightGlobals.ActiveVessel=new Vessel();FlightGlobals.Vessels.Add(FlightGlobals.ActiveVessel);var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded&&f.R.amount==9,"selected loaded vessel");});
Test("stale saved BRP mirror never overrides newer loaded production",()=>{var f=Fixture(mirror:true);var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded&&g.Synchronize(p).Succeeded,"stale mirror apply");var i=f.B.Inventories[0];Check(f.R.amount==9&&i.Amount==9&&i.OriginalAmount==9&&i.Snapshot.amount==9&&i.Snapshot.resourceValues.GetValues("amount")[0]=="9","all selected witnesses synchronized");Check(i.Amount+f.R.amount-i.OriginalAmount==9,"BRP restoration formula cannot double count");});
Test("confirmed rollback restores independent physical/provider/snapshot baselines",()=>{var f=Fixture(mirror:true);var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded,"apply");Check(g.Rollback(p).Confirmed,"rollback");var i=f.B.Inventories[0];Check(f.R.amount==10&&i.Amount==5&&i.OriginalAmount==5&&i.Snapshot.amount==5&&i.Snapshot.resourceValues.GetValues("amount")[0]=="5","each original witness restored");});
Test("unselected visitor tank remains unchanged",()=>{var f=Fixture(mirror:true);var visitor=new PartResource {resourceName="Ore",amount=13,maxAmount=100};f.V.parts.Add(new Part {persistentId=8,flightID=80,Resources=[visitor]});var g=new LoadedBrpInventoryGateway();Check(g.Apply(Prepare(g,f.E)).Succeeded&&visitor.amount==13,"visitor untouched");});
Test("locked source rejects debit",()=>{var f=Fixture();f.R.flowState=false;var g=new LoadedBrpInventoryGateway();var p=g.Preflight(g.Resolve(f.E),[new InventoryDelta {MemberPersistentId=7,ResourceName="Ore",DeltaMicroUnits=-1000000}]);Check(!p.Accepted&&f.R.amount==10,"lock guard");});
Test("locked destination may receive supported credit",()=>{var f=Fixture();f.R.flowState=false;var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E,1000000);Check(g.Apply(p).Succeeded&&g.Synchronize(p).Succeeded&&f.R.amount==11,"credit does not use flow network");});
Test("duplicate selected persistent identity elsewhere rejects resolution",()=>{var f=Fixture();FlightGlobals.Vessels.Add(new Vessel {loaded=false,protoVessel=new ProtoVessel {protoPartSnapshots=[new ProtoPartSnapshot {persistentId=7,flightID=700}]}});Check(new LoadedBrpInventoryGateway().Resolve(f.E)==null,"global uniqueness");});
Test("packed lifecycle change fences stale plan",()=>{var f=Fixture();var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);f.V.packed=true;Check(!g.Apply(p).Succeeded&&f.R.amount==10,"packed boundary");});
Test("resource modification between preflight and commit fences debit",()=>{var f=Fixture();var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);f.R.amount=11;Check(!g.Apply(p).Succeeded&&f.R.amount==11,"fresh amount fence");});
Test("same loaded plan cannot debit twice",()=>{var f=Fixture();var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);Check(g.Apply(p).Succeeded&&!g.Apply(p).Succeeded&&f.R.amount==9,"attempt identity");});
Test("unloaded gateway catches up before inventory read then syncs provider/config",()=>{var f=Fixture(mirror:true,amount:5);f.V.loaded=false;int caught=0;f.B.OnCatchup=()=>caught++;var g=new RemoteBrpInventoryGateway();var r=g.Resolve(f.E);Check(r!=null&&caught==1,"catch-up");var p=g.Preflight(r,[new InventoryDelta {MemberPersistentId=7,ResourceName="Ore",DeltaMicroUnits=-1000000}]);Check(p.Accepted,p.Reason);Check(g.Apply(p.Plan).Succeeded&&g.Synchronize(p.Plan).Succeeded,"remote exact provider");Check(f.B.Inventories[0].Amount==4&&f.B.Inventories[0].Snapshot.amount==4,"remote inventory debit");});
Test("remote provider snapshot mismatch holds without mutation",()=>{var f=Fixture(mirror:true,amount:5);f.V.loaded=false;f.B.Inventories[0].Amount=6;Check(new RemoteBrpInventoryGateway().Resolve(f.E)==null&&f.B.Inventories[0].Snapshot.amount==5,"coherence hold");});
Test("physical-to-colony durable hold precedes provider callback save",()=>{var f=Fixture(true);Check(PhysicalInventoryTransfers.TryPrepare("op-a","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);string ledger="before",saved=null;f.B.OnDirty=()=>saved=ledger;var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>true,CommitDurableHold=()=>ledger="held",CommitSuccess=()=>ledger="credited-once",RestoreBeforeAfterConfirmedRollback=()=>ledger="before"});Check(result.Outcome=="accepted"&&saved=="held"&&ledger=="credited-once"&&f.R.amount==9,"save sees terminal hold before credit");Check(PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary()).Outcome=="held"&&f.R.amount==9,"repeated operation does not debit");});
Test("failed provider callback plus confirmed rollback restores ledger and stock",()=>{var f=Fixture();Check(PhysicalInventoryTransfers.TryPrepare("op-b","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);string ledger="before";f.B.OnDirty=()=>throw new Exception("injected provider failure");var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>true,CommitDurableHold=()=>ledger="held",CommitSuccess=()=>ledger="credited",RestoreBeforeAfterConfirmedRollback=()=>ledger="before"});Check(result.Outcome=="rejected"&&f.R.amount==10&&ledger=="before","conserved rollback");});
Test("provider context loss retains durable hold without blind refund",()=>{var f=Fixture();Check(PhysicalInventoryTransfers.TryPrepare("op-c","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);string ledger="before";f.B.OnDirty=()=>{DepotRegistryModule.Instance=new DepotRegistryModule();throw new Exception("injected selected-world loss");};var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>true,CommitDurableHold=()=>ledger="held",CommitSuccess=()=>ledger="credited",RestoreBeforeAfterConfirmedRollback=()=>ledger="refunded"});Check(result.Outcome=="uncertain"&&ledger=="held"&&f.R.amount==9,"uncertainty conservatively held");});
Test("fractional free capacity cannot overpromise a micro-unit credit",()=>{var f=Fixture(amount:99.9999999);Check(!PhysicalInventoryTransfers.TryPrepare("op-d","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1}],false,out _,out _),"fractional micro unit free space");});
Test("stale registry rejects prepared transfer before durable hold or provider write",()=>{var f=Fixture();Check(PhysicalInventoryTransfers.TryPrepare("op-e","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);DepotRegistryModule.Instance.Registrations[0].MembershipRevision++;int writes=0;var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>true,CommitDurableHold=()=>writes++,CommitSuccess=()=>writes++,RestoreBeforeAfterConfirmedRollback=()=>writes++});Check(result.Outcome=="held"&&writes==0&&f.R.amount==10,"no stale write");});
Test("missing ledger boundary cannot mutate physical inventory",()=>{var f=Fixture();Check(PhysicalInventoryTransfers.TryPrepare("op-f","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);Check(PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary()).Outcome=="held"&&f.R.amount==10,"mandatory durable ledger contract");});
Test("late BRP save mirror invalidates a plan prepared while inventories were clear",()=>{var f=Fixture();var g=new LoadedBrpInventoryGateway();var p=Prepare(g,f.E);f.B.Inventories.Add(new ResourceInventory {FlightId=70,ResourceName="Ore",Amount=10,OriginalAmount=10,MaxAmount=100});Check(!g.Apply(p).Succeeded&&f.R.amount==10,"mirror lifecycle is re-resolved before writing");});
Test("specific service target fills only its registered part",()=>{var f=Fixture();var target=new PartResource {resourceName="Ore",amount=0,maxAmount=100};f.V.parts.Add(new Part {persistentId=8,flightID=80,Resources=[target]});DepotRegistryModule.Instance.Registrations[0].MemberIds.Add(8);Check(PhysicalInventoryTransfers.TryPrepare("service-exact","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],false,out var p,out var reason,8),reason);string ledger="before";var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>true,CommitDurableHold=()=>ledger="held",CommitSuccess=()=>ledger="debited",RestoreBeforeAfterConfirmedRollback=()=>ledger="before"});Check(result.Outcome=="accepted"&&ledger=="debited"&&target.amount==1&&f.R.amount==10,"target member only");});
Test("specific service target cannot spill into another tank when full",()=>{var f=Fixture();var target=new PartResource {resourceName="Ore",amount=100,maxAmount=100};f.V.parts.Add(new Part {persistentId=8,flightID=80,Resources=[target]});DepotRegistryModule.Instance.Registrations[0].MemberIds.Add(8);Check(!PhysicalInventoryTransfers.TryPrepare("service-full","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],false,out _,out _,8)&&f.R.amount==10,"no unrelated warehouse spill");});
Test("service target outside registered membership is rejected",()=>{Fixture();Check(!PhysicalInventoryTransfers.TryPrepare("service-foreign","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],false,out _,out _,999),"foreign target membership");});
Test("successful synchronization with lost ledger context keeps durable hold",()=>{var f=Fixture();Check(PhysicalInventoryTransfers.TryPrepare("op-sync-loss","source",[new ResourceAmount {ResourceName="Ore",AmountMicroUnits=1000000}],true,out var p,out var reason),reason);string ledger="before";bool current=true;f.B.OnDirty=()=>current=false;var result=PhysicalInventoryTransfers.Commit(p,new PhysicalInventoryCommitBoundary {IsCurrent=()=>current,CommitDurableHold=()=>ledger="held",CommitSuccess=()=>ledger="credited",RestoreBeforeAfterConfirmedRollback=()=>ledger="refunded"});Check(result.Outcome=="uncertain"&&ledger=="held"&&f.R.amount==9,"post-sync context fence");});
SelectedRegistryChecks.Run(Test);
Console.WriteLine("Adapter checks passed: "+passed+" / "+total+"; source-linked stubs only, actual KSP persistence qualification pending.");
